# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PUTLAB.VinPUT
PackageVersion: 0.3.4
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Interactive: --install
  Silent: --install --quiet
  SilentWithProgress: --install --quiet
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: VinPUT
  Publisher: PUTLAB
  DisplayVersion: 0.3.4
  ProductCode: Vinput
Installers:
- Architecture: x64
  InstallerUrl: https://vinput-dasvcr.web.app/releases/VinputSetup-0.3.4.exe
  InstallerSha256: 342FE2BC8DE67BA25C7934C24ADBE455CFDE518852035E2E17209E75027302E2
ManifestType: installer
ManifestVersion: 1.12.0
